

/*
use handlebars::{
    Context, Handlebars, Helper, HelperDef, HelperResult, JsonRender, Output, RenderContext,
    RenderError,
};
use std::io::Write;

BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS
BY NOW THIS DONT DOES ANYTHING INSIDE OUR VIEWS

*/
